#!/bin/bash

################################################################################
# Ubuntu System Configuration - Master Installer
# Description: Automated Ubuntu system configuration script with interactive
#              selection, dynamic configuration, and reboot handling.
################################################################################

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_DIR="${SCRIPT_DIR}/configs"
LOG_DIR="${SCRIPT_DIR}/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="${LOG_DIR}/install_$(date +%Y%m%d_%H%M%S).log"
STATE_FILE="${SCRIPT_DIR}/.install_state"

# Source configuration and prompts functions
if [ -f "${SCRIPT_DIR}/config_prompts.sh" ]; then
    source "${SCRIPT_DIR}/config_prompts.sh"
else
    echo -e "${RED}Error: config_prompts.sh not found!${NC}"
    exit 1
fi

# Source Core Modules
source "${SCRIPT_DIR}/core/apt/apt.sh"
source "${SCRIPT_DIR}/core/apt/apt_packages.sh"
source "${SCRIPT_DIR}/core/flatpak/flatpak.sh"
source "${SCRIPT_DIR}/core/flatpak/flatpak_packages.sh"
source "${SCRIPT_DIR}/core/homebrew/homebrew.sh"
source "${SCRIPT_DIR}/core/homebrew/homebrew_packages.sh"
source "${SCRIPT_DIR}/core/node/node.sh"
source "${SCRIPT_DIR}/core/node/npm_packages.sh"
source "${SCRIPT_DIR}/core/zsh/zsh.sh"
source "${SCRIPT_DIR}/core/zsh/zsh_plugins.sh"
source "${SCRIPT_DIR}/core/runtimes/runtimes.sh"
source "${SCRIPT_DIR}/core/editors/editors.sh"

################################################################################
# Helper Functions
################################################################################

log_msg() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE" > /dev/null
}

print_step() {
    echo -e "\n${BLUE}==>${NC} ${BOLD}$1${NC}"
    log_msg "STEP: $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
    log_msg "SUCCESS: $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
    log_msg "ERROR: $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
    log_msg "WARNING: $1"
}

print_info() {
    echo -e "${CYAN}ℹ${NC} $1"
    log_msg "INFO: $1"
}

decode_shell_escaped_value() {
    python3 -c 'import shlex, sys
value = sys.argv[1]
try:
    tokens = shlex.split(value, posix=True)
    print(tokens[0] if tokens else "")
except Exception:
    print(value)' "$1"
}

load_state_file() {
    [ -f "$STATE_FILE" ] || return 0

    while IFS= read -r line; do
        # Skip empty lines and comments
        [ -z "$line" ] && continue
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ "$line" != *=* ]] && continue

        local key="${line%%=*}"
        local value="${line#*=}"
        local decoded_value=""

        # Accept only valid shell variable names
        [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue

        # Load only known state keys
        case "$key" in
            CONFIG_USERNAME|CONFIG_HOME|PART1_COMPLETION_DATE)
                decoded_value="$(decode_shell_escaped_value "$value")"
                printf -v "$key" '%s' "$decoded_value"
                export "$key"
                ;;
            INSTALL_GIT|INSTALL_BUILD_ESSENTIAL|INSTALL_GEDIT|INSTALL_FUSE|INSTALL_NVM_NODE|INSTALL_PNPM|INSTALL_DENO|INSTALL_BUN|INSTALL_HOMEBREW|INSTALL_GH_CLI|INSTALL_ZSH|INSTALL_OH_MY_ZSH|INSTALL_ZSH_PLUGINS|INSTALL_VSCODIUM|INSTALL_VSCODE|INSTALL_FLATPAK|INSTALL_WEZTERM|INSTALL_VIVALDI|INSTALL_BITWARDEN|INSTALL_STIMULATOR|FLATPAK_JUST_INSTALLED|PART1_COMPLETED|PART2_COMPLETED)
                if [[ "$value" == "true" || "$value" == "false" ]]; then
                    printf -v "$key" '%s' "$value"
                    export "$key"
                fi
                ;;
            *)
                ;;
        esac
    done < "$STATE_FILE"
}

save_state_file() {
    cat > "$STATE_FILE" <<EOF
# Generated by install.sh on $(date '+%Y-%m-%d %H:%M:%S')
CONFIG_USERNAME=$(printf '%q' "$CONFIG_USERNAME")
CONFIG_HOME=$(printf '%q' "$CONFIG_HOME")
INSTALL_GIT=${INSTALL_GIT:-false}
INSTALL_BUILD_ESSENTIAL=${INSTALL_BUILD_ESSENTIAL:-false}
INSTALL_GEDIT=${INSTALL_GEDIT:-false}
INSTALL_FUSE=${INSTALL_FUSE:-false}
INSTALL_NVM_NODE=${INSTALL_NVM_NODE:-false}
INSTALL_PNPM=${INSTALL_PNPM:-false}
INSTALL_DENO=${INSTALL_DENO:-false}
INSTALL_BUN=${INSTALL_BUN:-false}
INSTALL_HOMEBREW=${INSTALL_HOMEBREW:-false}
INSTALL_GH_CLI=${INSTALL_GH_CLI:-false}
INSTALL_ZSH=${INSTALL_ZSH:-false}
INSTALL_OH_MY_ZSH=${INSTALL_OH_MY_ZSH:-false}
INSTALL_ZSH_PLUGINS=${INSTALL_ZSH_PLUGINS:-false}
INSTALL_VSCODIUM=${INSTALL_VSCODIUM:-false}
INSTALL_VSCODE=${INSTALL_VSCODE:-false}
INSTALL_FLATPAK=${INSTALL_FLATPAK:-false}
INSTALL_WEZTERM=${INSTALL_WEZTERM:-false}
INSTALL_VIVALDI=${INSTALL_VIVALDI:-false}
INSTALL_BITWARDEN=${INSTALL_BITWARDEN:-false}
INSTALL_STIMULATOR=${INSTALL_STIMULATOR:-false}
FLATPAK_JUST_INSTALLED=${FLATPAK_JUST_INSTALLED:-false}
PART1_COMPLETED=${PART1_COMPLETED:-false}
PART1_COMPLETION_DATE=$(printf '%q' "$PART1_COMPLETION_DATE")
PART2_COMPLETED=${PART2_COMPLETED:-false}
EOF
}



infer_bool_from_command() {
    if command -v "$1" >/dev/null 2>&1; then
        echo true
    else
        echo false
    fi
}

recover_state_from_system() {
    local fallback_user="${SUDO_USER:-$USER}"
    local fallback_home=""

    fallback_home="$(getent passwd "$fallback_user" | cut -d: -f6)"
    [ -n "$fallback_home" ] || fallback_home="$HOME"

    # Minimal heuristic: if core pre-reboot tools are present, infer Part 1 completion
    local git_ok=false
    local zsh_ok=false
    local flatpak_ok=false

    command -v git >/dev/null 2>&1 && git_ok=true
    command -v zsh >/dev/null 2>&1 && zsh_ok=true
    command -v flatpak >/dev/null 2>&1 && flatpak_ok=true

    if [ "$git_ok" != true ] || [ "$zsh_ok" != true ] || [ "$flatpak_ok" != true ]; then
        return 1
    fi

    CONFIG_USERNAME="$fallback_user"
    CONFIG_HOME="$fallback_home"

    INSTALL_ZSH="$(infer_bool_from_command zsh)"
    INSTALL_VSCODIUM="$(infer_bool_from_command codium)"
    INSTALL_VSCODE="$(infer_bool_from_command code)"
    INSTALL_FLATPAK="$(infer_bool_from_command flatpak)"

    if command -v flatpak >/dev/null 2>&1 && flatpak info org.wezfurlong.wezterm >/dev/null 2>&1; then
        INSTALL_WEZTERM=true
    else
        INSTALL_WEZTERM=false
    fi

    if command -v flatpak >/dev/null 2>&1 && flatpak info com.vivaldi.Vivaldi >/dev/null 2>&1; then
        INSTALL_VIVALDI=true
    else
        INSTALL_VIVALDI=false
    fi

    if command -v flatpak >/dev/null 2>&1 && flatpak info com.bitwarden.desktop >/dev/null 2>&1; then
        INSTALL_BITWARDEN=true
    else
        INSTALL_BITWARDEN=false
    fi

    if command -v flatpak >/dev/null 2>&1 && flatpak info io.github.sigmasd.stimulator >/dev/null 2>&1; then
        INSTALL_STIMULATOR=true
    else
        INSTALL_STIMULATOR=false
    fi

    FLATPAK_JUST_INSTALLED=false
    PART1_COMPLETED=true
    PART1_COMPLETION_DATE="$(date)"
    PART2_COMPLETED=${PART2_COMPLETED:-false}

    save_state_file
    return 0
}

part1_already_completed() {
    if [ ! -f "$STATE_FILE" ]; then
        recover_state_from_system || return 1
    else
        load_state_file
    fi

    [ "$PART1_COMPLETED" = true ]
}

ensure_sudo() {
    if [ "$EUID" -ne 0 ]; then
        print_warning "Esta operação requer privilégios de superusuário."
        echo -e "${CYAN}Por favor, digite sua senha quando solicitado.${NC}"
        if ! sudo -v; then
            print_error "Falha ao obter privilégios sudo"
            exit 1
        fi
        # Keep sudo alive
        while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
    fi
}

################################################################################
# Part 1: Pre-Reboot Installation Steps
################################################################################

run_part1() {
    print_step "Starting Part 1: Pre-Reboot Setup"
    
    # 1. APT Setup & Packages
    setup_apt
    install_apt_packages

    # 2. Node.js
    setup_node

    # 3. Runtimes (Deno/Bun + CLIs)
    install_runtimes

    # 4. Global JS Packages
    install_npm_packages

    # 5. Zsh Setup
    setup_zsh
    install_zsh_plugins

    # 6. Homebrew
    setup_homebrew
    install_homebrew_packages

    # 7. Editors
    install_editors

    # 8. Flatpak Setup (System)
    setup_flatpak

    # Save state
    PART1_COMPLETED=true
    PART1_COMPLETION_DATE="$(date)"
    save_state_file
    
    print_success "Part 1 completed successfully!"
}

################################################################################
# Part 2: Post-Reboot Installation Steps
################################################################################

run_part2() {
    print_step "Starting Part 2: Post-Reboot Setup"
    
    # Load state if variables are missing
    if [ -z "$CONFIG_USERNAME" ] && [ -f "$STATE_FILE" ]; then
        load_state_file
    fi
    
    if [ -z "$CONFIG_USERNAME" ]; then
        print_warning "State file incompleto/ausente. Tentando fallback por detecção do sistema..."
        recover_state_from_system
        load_state_file
    fi

    if [ -z "$CONFIG_USERNAME" ]; then
        print_error "Configuration missing. Cannot proceed with Part 2."
        exit 1
    fi

    # 1. Install Flatpak Apps
    install_flatpak_packages

    # 2. Copy Config Files
    print_step "Copying configuration files"
    if [ -d "$CONFIG_DIR" ]; then
        [ -f "$CONFIG_DIR/.zshrc" ] && sudo -u "$CONFIG_USERNAME" cp "$CONFIG_DIR/.zshrc" "${CONFIG_HOME}/.zshrc"
        [ -f "$CONFIG_DIR/.spaceshiprc.zsh" ] && sudo -u "$CONFIG_USERNAME" cp "$CONFIG_DIR/.spaceshiprc.zsh" "${CONFIG_HOME}/.spaceshiprc.zsh"
        [ -f "$CONFIG_DIR/wezterm.lua" ] && [ "$INSTALL_WEZTERM" = true ] && sudo -u "$CONFIG_USERNAME" cp "$CONFIG_DIR/wezterm.lua" "${CONFIG_HOME}/.wezterm.lua"
        print_success "Configuration files copied"
    fi

    # 3. Fix Zsh Permissions
    if [ "$INSTALL_ZSH" = true ]; then
        print_step "Fixing Zsh permissions"
        # Simple fix for common insecure directories
        sudo -u "$CONFIG_USERNAME" chmod 755 "${CONFIG_HOME}/.oh-my-zsh" "${CONFIG_HOME}/.oh-my-zsh/custom" 2>/dev/null
        print_success "Permissions fixed"
    fi

    # 4. Configure GNOME Favorites
    print_step "Configuring GNOME Favorites"
    local favorites="['org.gnome.Nautilus.desktop'"
    [ "$INSTALL_WEZTERM" = true ] && favorites+=", 'org.wezfurlong.wezterm.desktop'"
    [ "$INSTALL_VIVALDI" = true ] && favorites+=", 'com.vivaldi.Vivaldi.desktop'"
    [ "$INSTALL_VSCODIUM" = true ] && favorites+=", 'codium.desktop'"
    [ "$INSTALL_VSCODE" = true ] && favorites+=", 'code.desktop'"
    favorites+="]"
    
    sudo -u "$CONFIG_USERNAME" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u "$CONFIG_USERNAME")/bus" gsettings set org.gnome.shell favorite-apps "$favorites" 2>/dev/null
    print_success "Favorites configured"

    # 5. Configure WezTerm Default & Shortcuts
    if [ "$INSTALL_WEZTERM" = true ]; then
        print_step "Configuring WezTerm"
        sudo -u "$CONFIG_USERNAME" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u "$CONFIG_USERNAME")/bus" gsettings set org.gnome.desktop.default-applications.terminal exec 'flatpak run org.wezfurlong.wezterm' 2>/dev/null
        
        print_info "Note: Keyboard shortcuts configuration skipped in simplified installer. Please configure manually if needed."
    fi

    # Cleanup
    PART2_COMPLETED=true
    save_state_file
    
    # Remove service if exists
    if [ -f "/etc/systemd/system/ubuntu-setup-part2.service" ]; then
        systemctl disable ubuntu-setup-part2.service 2>/dev/null
        rm -f "/etc/systemd/system/ubuntu-setup-part2.service"
        systemctl daemon-reload
    fi

    print_success "Part 2 completed successfully!"
    echo -e "\n${GREEN}${BOLD}Installation Complete! Please log out and log back in.${NC}\n"
}

################################################################################
# Reboot Handling
################################################################################

handle_reboot() {
    echo -e "\n${YELLOW}${BOLD}REBOOT REQUIRED${NC}"
    echo -e "${CYAN}A reboot is necessary to complete the installation (Flatpak setup).${NC}"
    
    read -p "Do you want to reboot now and continue automatically? (Y/n): " choice
    if [[ "$choice" =~ ^[Nn] ]]; then
        print_warning "Reboot skipped. Please run './install.sh --post-reboot' after you reboot manually."
    else
        # Create auto-run service
        local service_file="/etc/systemd/system/ubuntu-setup-part2.service"
        cat <<EOF > "$service_file"
[Unit]
Description=Ubuntu System Setup - Part 2
After=network.target graphical.target
Wants=graphical.target

[Service]
Type=oneshot
ExecStart=$(readlink -f "$0") --post-reboot
StandardOutput=journal
StandardError=journal
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
        systemctl enable ubuntu-setup-part2.service
        print_success "Auto-run service created."
        print_step "Rebooting in 5 seconds..."
        sleep 5
        reboot
    fi
}

################################################################################
# Main Entry Point
################################################################################

main() {
    ensure_sudo

    # Check for post-reboot flag
    if [ "$1" == "--post-reboot" ]; then
        run_part2
        exit 0
    fi

    # If pre-reboot setup is already done, skip directly to post-reboot
    if part1_already_completed; then
        print_info "Part 1 já foi concluída anteriormente. Pulando para pós-reboot."
        run_part2
        exit 0
    fi

    # Interactive Setup
    run_configuration

    # Run Part 1
    run_part1

    # Check if reboot needed
    if grep -q "FLATPAK_JUST_INSTALLED=true" "$STATE_FILE" 2>/dev/null; then
        handle_reboot
    else
        # If no reboot needed, run Part 2 immediately
        run_part2
    fi
}

main "$@"
